name: Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [
            # '8', Refs: https://github.com/nulab/zxcvbn4j/pull/104
            '11',
            # '17' Refs: https://github.com/nulab/zxcvbn4j/issues/118
        ]
      fail-fast: false
    name: Build and test on JDK ${{ matrix.Java }}
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
      - name: Run gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: jacocoTestReport coveralls verGJF checkstyleMain spotbugsMain publishToMavenLocal
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}